version: "3.9"
services:
  lavalink:
    image: "ghcr.io/delxhq/soup-lavalink-image:main"
    hostname: lavalink
    networks:
      - soup
    environment:
      - "LAVALINK_SERVER_YOUTUBE_CONFIG_EMAIL=${GOOGLE_EMAIL}"
      - "LAVALINK_SERVER_YOUTUBE_CONFIG_PASSWORD=${GOOGLE_PASSWORD}"

  bot1:
    image: "ghcr.io/delxhq/soup:latest"
    networks:
      - soup
    environment:
      - "DISCORD_TOKEN=${TOKEN_1}"
      - "SPOTIFY_CLIENTID=${SPOTIFY_CLIENT}"
      - "SPOTIFY_CLIENTSECRET=${SPOTIFY_SECRET}"
      - "LAVALINK_HOST=lavalink"
      - "LAVALINK_PORT=2333"
      - "LOGS_CHANNEL=897300434094522379"
      - "STATISTICS_CHANNEL=908292838867992586"
      - "NODE_ENV=production"
  bot2:
    image: "ghcr.io/delxhq/soup:latest"
    networks:
      - soup
    environment:
      - "DISCORD_TOKEN=${TOKEN_2}"
      - "SPOTIFY_CLIENTID=${SPOTIFY_CLIENT}"
      - "SPOTIFY_CLIENTSECRET=${SPOTIFY_SECRET}"
      - "LAVALINK_HOST=lavalink"
      - "LAVALINK_PORT=2333"
      - "LOGS_CHANNEL=897300434094522379"
      - "STATISTICS_CHANNEL=908292838867992586"
      - "NODE_ENV=production"
  bot3:
    image: "ghcr.io/delxhq/soup:latest"
    networks:
      - soup
    environment:
      - "DISCORD_TOKEN=${TOKEN_3}"
      - "SPOTIFY_CLIENTID=${SPOTIFY_CLIENT}"
      - "SPOTIFY_CLIENTSECRET=${SPOTIFY_SECRET}"
      - "LAVALINK_HOST=lavalink"
      - "LAVALINK_PORT=2333"
      - "LOGS_CHANNEL=897300434094522379"
      - "STATISTICS_CHANNEL=908292838867992586"
      - "NODE_ENV=production"
networks:
  soup:
    driver: host
    enable_ipv6: true
    ipam:
       config:
         - subnet: 2001:41d0:801:2000::8e2/64
