export enum VoiceState {
  CONNECTED     = 'CONNECTED',
  CONNECTING    = 'CONNECTING',
  DISCONNECTED  = 'DISCONNECTED',
  DISCONNECTING = 'DISCONNECTING',
  DESTROYING    = 'DESTROYING',
}

export enum LoadType {
  TRACK_LOADED    = 'TRACK_LOADED',
  PLAYLIST_LOADED = 'PLAYLIST_LOADED',
  SEARCH_RESULT   = 'SEARCH_RESULT',
  LOAD_FAILED     = 'LOAD_FAILED',
  NO_MATCHES      = 'NO_MATCHES',
}