name: publish
on: [push]

jobs:
  build-soup-image:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install Node
      uses: actions/setup-node@v1
      with:
        node-version: 17
    - name: Install packages
      run: npm i
    - name: tsc
      uses: icrawl/action-tsc@v1

    - name: Build
      uses: iCrawl/action-tsc@v1

    - name: Delete build tools
      run: |
       rm -rf src

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build the Soup Docker image
      run: |
        docker build . --tag ghcr.io/delxhq/soup:latest
        docker push ghcr.io/delxhq/soup:latest
