name: publish

on:
  push:
    branches:
      - main

jobs:
  publish-soup-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build the Soup Docker image
      run: |
        docker build . --tag ghcr.io/delxhq/soup:latest
        docker push ghcr.io/delxhq/soup:latest
