name: publish
on: [push]

jobs:
  build-soup-image:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 17

    - name: Install packages
      run: npm install

    - name: Build source
      run: tsc --build

    - name: Delete Typescript
      run: rm -rf src

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build the Soup Docker image
      run: |
        docker build . --tag ghcr.io/delxhq/soup:latest
        docker push ghcr.io/delxhq/soup:latest
